# Laboratory Task 5
1. Perform Standard Imports


2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.


3. Create a NumPy array called “arr” that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.


4. Create a tensor “x” from the array above


5. Change the dtype of x from int32 to int64


6. Reshape x into a 3x2 tensor
There are several ways to do this.


7. Return the right-hand column of tensor x


8. Without changing x, return a tensor of square values of x
There are several ways to do this.


9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.


10. Find the matrix product of x and y.

## Laboratory Task 5

### 1. Standard Imports

In [1]:
import numpy as np
import torch
import random

### 2. Set Seed Function

In [2]:
def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

### 3. NumPy Array

In [3]:
set_seed(42)

arr = np.random.randint(0, 5, size=6)

print("arr:", arr)
print("dtype:", arr.dtype)

arr: [3 4 2 4 4 1]
dtype: int32


### 4. Tensor x From Array

In [4]:
x = torch.from_numpy(arr)

print("x:", x)
print("dtype:", x.dtype)
print("shape:", x.shape)

x: tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
dtype: torch.int32
shape: torch.Size([6])


### 5. Change int32 to int64

In [5]:
x = x.to(torch.int64)

print("x:", x)
print("dtype:", x.dtype)

x: tensor([3, 4, 2, 4, 4, 1])
dtype: torch.int64


### 6. Reshape

In [6]:
# Option A — .reshape()

x = x.reshape(3, 2)

print("x:\n", x)
print("shape:", x.shape)

x:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])
shape: torch.Size([3, 2])


### 7. Right Hand Column of x

In [7]:
right_col = x[:, -1]

print("right column:", right_col)

right column: tensor([4, 4, 1])


### 8. Square Values

In [8]:
# Option A — torch.square()

x_squared = torch.square(x)

print("x squared:\n", x_squared)
print("x unchanged:\n", x)

x squared:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
x unchanged:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 9. Create Tensor y Matrix-Multipliable With x

In [9]:
set_seed(42)

y = torch.randint(0, 5, (2, 3))

print("y:\n", y)
print("shape:", y.shape)

y:
 tensor([[2, 2, 1],
        [4, 1, 0]])
shape: torch.Size([2, 3])


### 10. Matrix Product

In [10]:
result = x @ y

print("x @ y:\n", result)
print("shape:", result.shape)

x @ y:
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
shape: torch.Size([3, 3])
